name: Linter

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install deps
        run: |
          yarn install

      - name: lint
        run: |
          yarn lint
