name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install deps
        run: |
          yarn install

      - name: build
        run: |
          yarn build

      - name: test
        run: |
          yarn test
